#############################################################################
# Makefile for building: qt_interface_cuda
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri May 10 00:01:10 2013
# Project:  qt_interface_cuda.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qt_interface_cuda.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I/usr/local/cuda-5.0/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lcudart -lcuda -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = ${OBJECTS_DIR}mycuda_cuda.o \
		main.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qt_interface_cuda.pro
QMAKE_TARGET  = qt_interface_cuda
DESTDIR       = 
TARGET        = qt_interface_cuda

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_interface_cuda.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile qt_interface_cuda.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qt_interface_cuda.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt_interface_cuda1.0.0 || $(MKDIR) .tmp/qt_interface_cuda1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt_interface_cuda1.0.0/ && $(COPY_FILE) --parents mycuda.cu .tmp/qt_interface_cuda1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/qt_interface_cuda1.0.0/ && (cd `dirname .tmp/qt_interface_cuda1.0.0` && $(TAR) qt_interface_cuda1.0.0.tar qt_interface_cuda1.0.0 && $(COMPRESS) qt_interface_cuda1.0.0.tar) && $(MOVE) `dirname .tmp/qt_interface_cuda1.0.0`/qt_interface_cuda1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt_interface_cuda1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_cuda_make_all: ${OBJECTS_DIR}mycuda_cuda.o
compiler_cuda_clean:
	-$(DEL_FILE) ${OBJECTS_DIR}mycuda_cuda.o
${OBJECTS_DIR}mycuda_cuda.o: mycuda.cu \
		mycuda.cu \
		/usr/local/cuda-5.0/include/cuda_runtime.h \
		/usr/local/cuda-5.0/include/host_config.h \
		/usr/include/features.h \
		/usr/include/x86_64-linux-gnu/bits/predefs.h \
		/usr/include/x86_64-linux-gnu/sys/cdefs.h \
		/usr/include/x86_64-linux-gnu/bits/wordsize.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs.h \
		/usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.4/include-fixed/limits.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.4/include-fixed/syslimits.h \
		/usr/include/limits.h \
		/usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
		/usr/include/x86_64-linux-gnu/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
		/usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
		/usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.4/include/stddef.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/driver_functions.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/common_functions.h \
		/usr/include/string.h \
		/usr/include/xlocale.h \
		/usr/include/x86_64-linux-gnu/bits/string3.h \
		/usr/include/time.h \
		/usr/include/x86_64-linux-gnu/bits/time.h \
		/usr/include/x86_64-linux-gnu/bits/types.h \
		/usr/include/x86_64-linux-gnu/bits/typesizes.h \
		/usr/include/x86_64-linux-gnu/bits/timex.h \
		/usr/include/c++/4.4/new \
		/usr/include/c++/4.4/cstddef \
		/usr/include/c++/4.4/x86_64-linux-gnu/bits/c++config.h \
		/usr/include/c++/4.4/x86_64-linux-gnu/bits/os_defines.h \
		/usr/include/c++/4.4/x86_64-linux-gnu/bits/cpu_defines.h \
		/usr/include/c++/4.4/exception \
		/usr/local/cuda-5.0/include/math_functions.h \
		/usr/include/math.h \
		/usr/include/x86_64-linux-gnu/bits/huge_val.h \
		/usr/include/x86_64-linux-gnu/bits/huge_valf.h \
		/usr/include/x86_64-linux-gnu/bits/huge_vall.h \
		/usr/include/x86_64-linux-gnu/bits/inf.h \
		/usr/include/x86_64-linux-gnu/bits/nan.h \
		/usr/include/x86_64-linux-gnu/bits/mathdef.h \
		/usr/include/x86_64-linux-gnu/bits/mathcalls.h \
		/usr/include/x86_64-linux-gnu/bits/mathinline.h \
		/usr/include/stdlib.h \
		/usr/include/x86_64-linux-gnu/bits/waitflags.h \
		/usr/include/x86_64-linux-gnu/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/x86_64-linux-gnu/bits/endian.h \
		/usr/include/x86_64-linux-gnu/bits/byteswap.h \
		/usr/include/x86_64-linux-gnu/sys/types.h \
		/usr/include/x86_64-linux-gnu/sys/select.h \
		/usr/include/x86_64-linux-gnu/bits/select.h \
		/usr/include/x86_64-linux-gnu/bits/sigset.h \
		/usr/include/x86_64-linux-gnu/bits/select2.h \
		/usr/include/x86_64-linux-gnu/sys/sysmacros.h \
		/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/x86_64-linux-gnu/bits/stdlib.h \
		/usr/include/c++/4.4/cmath \
		/usr/include/c++/4.4/bits/cpp_type_traits.h \
		/usr/include/c++/4.4/ext/type_traits.h \
		/usr/include/c++/4.4/bits/cmath.tcc \
		/usr/include/c++/4.4/cstdlib \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx1.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/device_functions.h \
		/usr/local/cuda-5.0/include/sm_11_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_12_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_13_double_functions.h \
		/usr/local/cuda-5.0/include/sm_20_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_35_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_20_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_30_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_35_intrinsics.h \
		/usr/local/cuda-5.0/include/surface_functions.h \
		/usr/local/cuda-5.0/include/texture_fetch_functions.h \
		/usr/local/cuda-5.0/include/texture_indirect_functions.h \
		/usr/local/cuda-5.0/include/surface_indirect_functions.h \
		/usr/local/cuda-5.0/include/device_launch_parameters.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.4/include/stdarg.h \
		/usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
		/usr/include/x86_64-linux-gnu/bits/stdio.h \
		/usr/include/x86_64-linux-gnu/bits/stdio2.h \
		/usr/local/cuda-5.0/include/cuda.h \
		/usr/local/cuda-5.0/include/host_config.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/driver_functions.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/common_functions.h \
		/usr/local/cuda-5.0/include/math_functions.h \
		/usr/local/cuda-5.0/include/math_constants.h \
		/usr/local/cuda-5.0/include/device_functions.h \
		/usr/local/cuda-5.0/include/sm_11_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_12_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_13_double_functions.h \
		/usr/local/cuda-5.0/include/sm_20_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_35_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_20_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_30_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_35_intrinsics.h \
		/usr/local/cuda-5.0/include/surface_functions.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/texture_fetch_functions.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/texture_indirect_functions.h \
		/usr/local/cuda-5.0/include/surface_indirect_functions.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx1.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-5.0/include/device_launch_parameters.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/lib/gcc/x86_64-linux-gnu/4.4/include-fixed/syslimits.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/math_functions.h \
		/usr/local/cuda-5.0/include/math_constants.h \
		/usr/local/cuda-5.0/include/device_functions.h \
		/usr/local/cuda-5.0/include/sm_11_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_12_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_13_double_functions.h \
		/usr/local/cuda-5.0/include/sm_20_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_35_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_20_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_30_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_35_intrinsics.h \
		/usr/local/cuda-5.0/include/surface_functions.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/texture_fetch_functions.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/texture_indirect_functions.h \
		/usr/local/cuda-5.0/include/surface_indirect_functions.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx1.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/math_constants.h \
		/usr/local/cuda-5.0/include/device_functions.h \
		/usr/local/cuda-5.0/include/sm_11_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_12_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_13_double_functions.h \
		/usr/local/cuda-5.0/include/sm_20_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_35_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_20_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_30_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_35_intrinsics.h \
		/usr/local/cuda-5.0/include/surface_functions.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/texture_fetch_functions.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/texture_indirect_functions.h \
		/usr/local/cuda-5.0/include/surface_indirect_functions.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx1.h \
		/usr/local/cuda-5.0/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/sm_11_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_12_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_13_double_functions.h \
		/usr/local/cuda-5.0/include/sm_20_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_35_atomic_functions.h \
		/usr/local/cuda-5.0/include/sm_20_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_30_intrinsics.h \
		/usr/local/cuda-5.0/include/sm_35_intrinsics.h \
		/usr/local/cuda-5.0/include/surface_functions.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/texture_fetch_functions.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/texture_indirect_functions.h \
		/usr/local/cuda-5.0/include/surface_indirect_functions.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/cuda_surface_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/cuda_texture_types.h \
		/usr/local/cuda-5.0/include/channel_descriptor.h \
		/usr/local/cuda-5.0/include/cuda_runtime_api.h \
		/usr/local/cuda-5.0/include/cuda_device_runtime_api.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/vector_functions.h \
		/usr/local/cuda-5.0/include/vector_types.h \
		/usr/local/cuda-5.0/include/builtin_types.h \
		/usr/local/cuda-5.0/include/device_types.h \
		/usr/local/cuda-5.0/include/host_defines.h \
		/usr/local/cuda-5.0/include/driver_types.h \
		/usr/local/cuda-5.0/include/surface_types.h \
		/usr/local/cuda-5.0/include/texture_types.h
	/usr/local/cuda/bin/nvcc -m64 -O3 -arch=sm_30 -c --compiler-options -use_fast_math -I. -I/usr/local/cuda/include -lcudart -lcuda mycuda.cu -o ${OBJECTS_DIR}mycuda_cuda.o

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

